
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Jul 23 12:23:44 CEST 2014
//----------------------------------------------------

package tiny;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 36;
  public static final int DISTINTO = 29;
  public static final int POR = 15;
  public static final int CCIERRE = 41;
  public static final int PCIERRE = 33;
  public static final int SUBPROGRAM = 8;
  public static final int DOUBLE = 39;
  public static final int CAP = 40;
  public static final int INT = 37;
  public static final int ARRAY = 47;
  public static final int ENDDO = 12;
  public static final int DELETE = 51;
  public static final int WRITE = 49;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int IGUAL = 24;
  public static final int NUMERO_NATURAL = 52;
  public static final int OR = 19;
  public static final int DIV = 16;
  public static final int IF = 9;
  public static final int ID = 54;
  public static final int PYCOMA = 30;
  public static final int BOOLEAN = 38;
  public static final int LLAVECIERRE = 35;
  public static final int EOF = 0;
  public static final int AMP = 44;
  public static final int ASIG = 23;
  public static final int MAYOROIGUAL = 28;
  public static final int TRUE = 45;
  public static final int NEW = 50;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int COMA = 31;
  public static final int NUMERO_REAL = 53;
  public static final int MENOS = 14;
  public static final int MENOR = 25;
  public static final int MOD = 17;
  public static final int TOINT = 21;
  public static final int MENOROIGUAL = 27;
  public static final int MAYOR = 26;
  public static final int PAP = 32;
  public static final int FLECHA = 43;
  public static final int ENDIF = 10;
  public static final int PUNTO = 42;
  public static final int VARIABLES = 6;
  public static final int READ = 48;
  public static final int LLAVEAP = 34;
  public static final int TYPES = 3;
  public static final int FALSE = 46;
  public static final int POINTER = 5;
  public static final int STRUCT = 4;
  public static final int TODOUBLE = 22;
  public static final int SUBPROGRAMS = 7;
  public static final int DO = 11;
  public static final int MAS = 13;
}

