package alex;

public enum ClaseLexica {
 IDEN, ENT, PAP, PCIERRE, IGUALASIG, PYC, 
 MAS, MENOS, POR, DIV, TRUE, FALSE, MAYORIGUAL,MENORIGUAL,DISTINTO,IGUALCOMP,MAYOR,MENOR
 ,BOOL,INT,SECCION,AND,OR,NOT, EOF
}
