
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon May 05 10:00:07 CEST 2014
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseSimbolos {
  /* terminals */
  public static final int PCIERRE = 5;
  public static final int AND = 23;
  public static final int MENOS = 9;
  public static final int MENOR = 19;
  public static final int PYC = 7;
  public static final int OR = 24;
  public static final int INT = 21;
  public static final int MENORIGUAL = 15;
  public static final int IGUALASIG = 6;
  public static final int NOT = 25;
  public static final int IDEN = 2;
  public static final int TRUE = 12;
  public static final int POR = 10;
  public static final int IGUALCOMP = 17;
  public static final int MAYOR = 18;
  public static final int DISTINTO = 16;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int MAYORIGUAL = 14;
  public static final int PAP = 4;
  public static final int FALSE = 13;
  public static final int error = 1;
  public static final int BOOL = 20;
  public static final int SECCION = 22;
  public static final int ENT = 3;
  public static final int MAS = 8;
}

