/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int INT = 1;
  int BOOL = 2;
  int AND = 3;
  int OR = 4;
  int NOT = 5;
  int TRUE = 6;
  int FALSE = 7;
  int letra = 8;
  int digitoPositivo = 9;
  int digito = 10;
  int parteEntera = 11;
  int seccion = 14;
  int subrayado = 15;
  int identificador = 16;
  int numeroEntero = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"int\"",
    "\"bool\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"&&\"",
    "\"_\"",
    "<identificador>",
    "<numeroEntero>",
    "\";\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"<=\"",
    "\">=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
